# SPDX-FileCopyrightText: © 2020 The birch-books-smarthome Authors
# SPDX-License-Identifier: MIT

BOOKSTORE_GROUND_FLOOR = 0x0007
BOOKSTORE_FIRST_FLOOR = 0x0008
BOOKSTORE_TERRARIUM = 0x0010
BOOKSTORE_BEDROOM = 0x0020
HOUSE_BASEMENT = 0x0040
HOUSE_GROUND_FLOOR = 0x0380
HOUSE_BEDROOM_LIGHT = 0x0400
HOUSE_BEDROOM_LAMP = 0x0800
HOUSE_FIREPLACE_1 = 0x1000
HOUSE_FIREPLACE_2 = 0x2000

SCHEDULE = [
    BOOKSTORE_BEDROOM | HOUSE_BEDROOM_LIGHT,
    BOOKSTORE_TERRARIUM | BOOKSTORE_BEDROOM | HOUSE_BEDROOM_LIGHT,
    BOOKSTORE_TERRARIUM | BOOKSTORE_FIRST_FLOOR | HOUSE_BEDROOM_LIGHT,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR | HOUSE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR | HOUSE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR | HOUSE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_FIRST_FLOOR | HOUSE_GROUND_FLOOR,
    BOOKSTORE_TERRARIUM | BOOKSTORE_FIRST_FLOOR | HOUSE_BASEMENT | HOUSE_BEDROOM_LIGHT,
    BOOKSTORE_TERRARIUM | BOOKSTORE_BEDROOM | HOUSE_BASEMENT | HOUSE_BEDROOM_LAMP,
    BOOKSTORE_BEDROOM | HOUSE_BEDROOM_LAMP,
    0,
    0,
]

TEST_SCHEDULE = [
    BOOKSTORE_GROUND_FLOOR,
    BOOKSTORE_FIRST_FLOOR,
    BOOKSTORE_TERRARIUM,
    BOOKSTORE_BEDROOM,
    HOUSE_BASEMENT,
    HOUSE_GROUND_FLOOR,
    HOUSE_BEDROOM_LIGHT,
    HOUSE_BEDROOM_LAMP,
    HOUSE_FIREPLACE_1,
    HOUSE_FIREPLACE_2,
]
