// SPDX-FileCopyrightText: © 2020 The birch-books-smarthome Authors
// SPDX-License-Identifier: MIT

#include <stdint.h>

/* Port-to-room mapping for the ATmega48-based Birch Books Controller.
 *
 * Unlike the 8051 version, the mapping is not linear. Instead the Ports C (0~5)
 * and D (0~7) are used.
 *
 * For convenience, Port C is expanded to 8 bits, with the two highest left at
 * 0.
 */
#define BOOKSTORE_GROUND_FLOOR 0x0007
#define BOOKSTORE_FIRST_FLOOR 0x0008
#define BOOKSTORE_TERRARIUM 0x0010
#define BOOKSTORE_BEDROOM 0x0020
#define HOUSE_BASEMENT 0x0100
#define HOUSE_GROUND_FLOOR 0x0E00
#define HOUSE_BEDROOM_LIGHT 0x1000
#define HOUSE_BEDROOM_LAMP 0x2000
#define HOUSE_FIREPLACE_1 0x4000
#define HOUSE_FIREPLACE_2 0x8000

static const uint16_t schedule[16] = {
    /* 00 */ BOOKSTORE_BEDROOM | HOUSE_BEDROOM_LIGHT,
    /* 01 */ BOOKSTORE_TERRARIUM | BOOKSTORE_BEDROOM | HOUSE_BEDROOM_LIGHT,
    /* 02 */ BOOKSTORE_TERRARIUM | BOOKSTORE_FIRST_FLOOR | HOUSE_BEDROOM_LIGHT,
    /* 03 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR | HOUSE_GROUND_FLOOR,
    /* 04 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR | HOUSE_GROUND_FLOOR,
    /* 05 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR, // 4 times
    /* 06 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    /* 07 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    /* 08 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR,
    /* 09 */ BOOKSTORE_TERRARIUM | BOOKSTORE_GROUND_FLOOR | HOUSE_GROUND_FLOOR,
    /* 10 */ BOOKSTORE_TERRARIUM | BOOKSTORE_FIRST_FLOOR | HOUSE_GROUND_FLOOR,
    /* 11 */ BOOKSTORE_TERRARIUM | BOOKSTORE_FIRST_FLOOR | HOUSE_BASEMENT |
        HOUSE_BEDROOM_LIGHT,
    /* 12 */ BOOKSTORE_TERRARIUM | BOOKSTORE_BEDROOM | HOUSE_BASEMENT |
        HOUSE_BEDROOM_LAMP,
    /* 13 */ BOOKSTORE_BEDROOM | HOUSE_BEDROOM_LAMP,
    /* 14 */ 0,
    /* 15 */ 0,
};

static const uint16_t test_schedule[10] = {
    BOOKSTORE_GROUND_FLOOR, BOOKSTORE_FIRST_FLOOR, BOOKSTORE_TERRARIUM,
    BOOKSTORE_BEDROOM,      HOUSE_BASEMENT,        HOUSE_GROUND_FLOOR,
    HOUSE_BEDROOM_LIGHT,    HOUSE_BEDROOM_LAMP,    HOUSE_FIREPLACE_1,
    HOUSE_FIREPLACE_2,
};
